export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'
export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR'

export const FETCH_CHATS_REQUEST = 'FETCH_CHATS_REQUEST'
export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS'
export const FETCH_CHATS_ERROR = 'FETCH_CHATS_ERROR'

export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'